# Generated by Django 4.2.3 on 2023-08-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройки публикации', 'verbose_name_plural': 'Настройки публикаций'},
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='log',
            name='attempt_status',
            field=models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка')], max_length=20, verbose_name='Статус отправки'),
        ),
    ]
