# Generated by Django 4.2.3 on 2023-08-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_options_alter_log_options_and_more'),
        ('mailing', '0002_initial'),
    ]

    operations = [
    ]
