# Generated by Django 4.2.3 on 2023-08-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('pk',), 'permissions': [('block_status', 'Block or unblock status')], 'verbose_name': 'Настройки публикации', 'verbose_name_plural': 'Настройки публикаций'},
        ),
    ]
